/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-05-11 14:57:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/jsp/footer.jsp", Long.valueOf(1652255974000L));
    _jspx_dependants.put("/jsp/../css/footer.css", Long.valueOf(1652280988000L));
    _jspx_dependants.put("/jsp/../css/app.css", Long.valueOf(1652280886000L));
    _jspx_dependants.put("/jsp/../css/login.css", Long.valueOf(1652263080000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    ");
      out.write("form {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    padding: 20px 25px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    min-width: 300px;\r\n");
      out.write("    max-width: 850px;\r\n");
      out.write("    border: 1px solid rgba(128 , 128 , 128 , 0.1);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 1px 1px 6px rgba(128 , 128 , 128 , 0.3);\r\n");
      out.write("    background-color: white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form h1 {\r\n");
      out.write("   flex: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("form hr {\r\n");
      out.write("    flex: 100%;\r\n");
      out.write("    display: block; height: 1px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-top: 1px solid rgba(128, 128, 128, 0.15);\r\n");
      out.write("    margin: 1em 0; padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form label{\r\n");
      out.write("    flex: 100% ;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("form input {\r\n");
      out.write("    flex: 100%  ;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border: 1px solid rgba(128 , 128 , 128 , 0.25);\r\n");
      out.write("    padding: 10px 12px;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 550px;\r\n");
      out.write("    margin: 8px 6px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("form button {\r\n");
      out.write("    flex: 100% ;\r\n");
      out.write("    margin: 8px 12px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 12px;\r\n");
      out.write("    background-color: rgba(30, 144 , 255, 0.7);\r\n");
      out.write("    border-radius: 7px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 350px;\r\n");
      out.write("    min-width: 200px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form input:hover,form input:focus{\r\n");
      out.write("    outline: 2px solid rgba(30, 144 , 255, 0.2);\r\n");
      out.write("    box-shadow: 1px 1px  7px rgba(30, 144 , 255, 0.4);\r\n");
      out.write("}\r\n");
      out.write("form button:hover {\r\n");
      out.write("    opacity: 0.85;\r\n");
      out.write("    box-shadow: 1px 1px 3px rgba(128, 128, 128, 0.8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');\r\n");
      out.write("* {\r\n");
      out.write("    font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("#dropdown-arrow {\r\n");
      out.write("    height: 0;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("    margin-left: 3px;\r\n");
      out.write("    border-left: 6px solid transparent;\r\n");
      out.write("    border-right: 6px solid transparent;\r\n");
      out.write("    border-top: 6px solid rgba(255, 255 , 255, 0.7);\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("#blue_segment {\r\n");
      out.write("    background-color: #47ccde;\r\n");
      out.write("    height: 30vh;\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    position: fixed ;\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write("    padding: 15px 30px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    height: 80vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    float: left;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 30px;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    min-width: 160px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("    float: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 12px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".show {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    border-bottom: 1px solid rgba(128, 128, 128, 0.7);\r\n");
      out.write("    background-color: black;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write(".navbar-left {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    padding-left: 12px;\r\n");
      out.write("}\r\n");
      out.write(".navbar-right {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: flex-end;\r\n");
      out.write("    padding-right: 12px;\r\n");
      out.write("}\r\n");
      out.write(".navbar__item {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("}\r\n");
      out.write(".navbar__item:hover, .navbar__item:focus {\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("    color: white;\r\n");
      out.write("    box-shadow: 1px 1px 5px rgba(128, 128, 128, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("    padding-top: 55px ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>First JSP</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"blue_segment\" >\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <form  action=\"/tour/login\" method=\"post\" >\r\n");
      out.write("        <h1>Login Form</h1>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <label > Username: </label>\r\n");
      out.write("        <input  type=\"text\" name=\"username\" placeholder=\"username\"  autocomplete=\"off\" />\r\n");
      out.write("        <label > Password: </label>\r\n");
      out.write("        <input  type=\"password\" name=\"password\" placeholder=\"password\" />\r\n");
      out.write("        <button type=\"submit\">Login</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    ");
      out.write(".footer {\r\n");
      out.write("    color: white;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    column-gap: 30px;\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    /*top: calc(100vh - 110px);*/\r\n");
      out.write("    background-color: black;\r\n");
      out.write("}\r\n");
      out.write(".footer__segment{\r\n");
      out.write("    min-width: 300px;\r\n");
      out.write("    padding: 15px 12px;\r\n");
      out.write("}\r\n");
      out.write(".footer__segment-header{\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".footer__item {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer__item:hover {\r\n");
      out.write("    opacity: 0.85;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider {\r\n");
      out.write("    border-left: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("    height: 60px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"footer__segment\">\r\n");
      out.write("        <div class=\"footer__segment-header\">About</div>\r\n");
      out.write("        <div class=\"footer__item\">SiteMap</div>\r\n");
      out.write("        <div class=\"footer__item\">Contact Us</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"divider\"></div>\r\n");
      out.write("    <div class=\"footer__segment\">\r\n");
      out.write("        <div class=\"footer__segment-header\">Services</div>\r\n");
      out.write("        <div class=\"footer__item\">How to Access</div>\r\n");
      out.write("        <div class=\"footer__item\">FAQ</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
